#ifndef SCENES_H
#define SCENES_H

#include "game_state.h"

typedef struct
{
  char text[100];
  int nextSceneId;
  int conditionalNextSceneId;
} Option;

typedef struct
{
  int SceneId;
  LocationID location;
  char description[350];
  int option_count;
  Option options[6];
  int success_rate_modifier;
  int gif_state_number;
  int option_index;
  int itemId;
  int clueId
} Scene;

typedef enum
{
  SCENE_OUTSIDE_START = 0,
  SCENE_OUTSIDE_RETURN,
  SCENE_ELEVATOR_MENU,

  SCENE_OFFICER_FIRST,
  SCENE_OFFICER_MENU,
  SCENE_OFFICER_RETURN,
  SCENE_ELEVATOR_DOWN,

  // Köket
  SCENE_KITCHEN_FIRST_TEXT,
  SCENE_KITCHEN_MENU,
  SCENE_KITCHEN_TABLET,
  SCENE_KITCHEN_EMPTY_TEXT,
  SCENE_KITCHEN_EMPTY_MENU,

  // Lösenord
  SCENE_KITCHEN_TABLET_LOCKED_TEXT,
  SCENE_KITCHEN_TABLET_LOCKED_MENU_NO_CLUE,
  SCENE_KITCHEN_TABLET_LOCKED_MENU_HAS_CLUE,
  SCENE_KITCHEN_TABLET_WRONG_PASSWORD_TEXT,
  SCENE_KITCHEN_TABLET_SUCCESS_TEXT,

  // Vardagsrummet
  SCENE_LIVING_ROOM_FIRST_TEXT,
  SCENE_LIVING_ROOM_MENU,
  SCENE_LIVING_ROOM_GUN,
  SCENE_LIVING_ROOM_EMPTY_TEXT,
  SCENE_LIVING_ROOM_EMPTY_MENU,

  // Sovrummet (Nytt)
  SCENE_BEDROOM_FIRST_TEXT,
  SCENE_BEDROOM_MENU,
  SCENE_BEDROOM_TABLET,
  SCENE_BEDROOM_EMPTY_TEXT,
  SCENE_BEDROOM_EMPTY_MENU,

  // Badrummet
  SCENE_BATHROOM_FIRST_TEXT,
  SCENE_BATHROOM_MENU,
  SCENE_BATHROOM_SEARCH,
  SCENE_BATHROOM_EMPTY_TEXT,
  SCENE_BATHROOM_EMPTY_MENU,

  // Balkongen
  SCENE_BALCONY_INTERMEDIARY_1,
  SCENE_BALCONY_START_TEXT,

  // QTE / Gun Tester
  SCENE_BALCONY_GUN_TESTER,
  SCENE_BALCONY_GUN_TESTER_TWO,

  // Menyer del 1
  SCENE_BALCONY_MENU_NONE,
  SCENE_BALCONY_MENU_NAME,
  SCENE_BALCONY_MENU_GUN,
  SCENE_BALCONY_MENU_BOTH,

  // Dialogövergångar del 1
  SCENE_BALCONY_CALL_NAME_TEXT,
  SCENE_BALCONY_ORDER_SURRENDER_TEXT,
  SCENE_BALCONY_DIALOGUE_1_TEXT,

  // Vapensluten
  SCENE_BALCONY_DRAW_GUN_SUCCESS_TEXT,
  SCENE_BALCONY_DRAW_GUN_FAIL_TEXT,
  SCENE_BALCONY_DRAW_GUN_KILL_EMMA_TEXT,

  // Intermediary för del 2
  SCENE_BALCONY_INTERMEDIARY_2,

  // Menyer del 2
  SCENE_BALCONY_DIALOGUE_1_MENU_NONE,
  SCENE_BALCONY_DIALOGUE_1_MENU_EMMA,

  // Dialogövergångar del 2
  SCENE_BALCONY_SYMPATHIZE_TEXT,
  SCENE_BALCONY_MENTION_EMMA_TEXT,
  SCENE_BALCONY_DEMAND_LET_GO_TEXT,

  // Final meny
  SCENE_BALCONY_DIALOGUE_2_MENU,

  // Sluten
  SCENE_BALCONY_CONVINCE_SUCCESS_TEXT,
  SCENE_BALCONY_CONVINCE_FAIL_TEXT,
  SCENE_BALCONY_SACRIFICE_TEXT,

  SCENE_ENDING_SUCCESS,
  SCENE_ENDING_YOU_DIE,
  SCENE_ENDING_YOU_DIE_EMMA_DIE,
  SCENE_ENDING_EMMA_DIE,

  TOTAL_SCENES
} SceneIndex;

extern const Scene story_scenes[];
#endif