#ifndef SCENES_H
#define SCENES_H

#include "game_state.h"

typedef struct
{
  char text[100];
  int nextSceneId;
  int conditionalNextSceneId;
} Option;

typedef struct
{
  int SceneId;
  LocationID location;
  char description[350];
  int option_count;
  Option options[6];
  int success_rate_modifier;
  int gif_state_number;
  int option_index;
  int itemId;
  int clueId
} Scene;

typedef enum
{
  SCENE_OUTSIDE_START = 0,
  SCENE_OUTSIDE_RETURN,
  SCENE_ELEVATOR_MENU,

  SCENE_OFFICER_FIRST,
  SCENE_OFFICER_MENU,
  SCENE_OFFICER_RETURN,
  SCENE_ELEVATOR_DOWN,

  // Köket
  SCENE_KITCHEN_FIRST_TEXT,
  SCENE_KITCHEN_MENU,
  SCENE_KITCHEN_TABLET,
  SCENE_KITCHEN_EMPTY_TEXT,
  SCENE_KITCHEN_EMPTY_MENU,

  // Vardagsrummet
  SCENE_LIVING_ROOM_FIRST_TEXT,
  SCENE_LIVING_ROOM_MENU,
  SCENE_LIVING_ROOM_GUN,
  SCENE_LIVING_ROOM_EMPTY_TEXT,
  SCENE_LIVING_ROOM_EMPTY_MENU,

  // Sovrummet (Nytt)
  SCENE_BEDROOM_FIRST_TEXT,
  SCENE_BEDROOM_MENU,
  SCENE_BEDROOM_TABLET,
  SCENE_BEDROOM_EMPTY_TEXT,
  SCENE_BEDROOM_EMPTY_MENU,

  // Badrummet
  SCENE_BATHROOM_FIRST_TEXT,
  SCENE_BATHROOM_MENU,
  SCENE_BATHROOM_SEARCH,
  SCENE_BATHROOM_EMPTY_TEXT,
  SCENE_BATHROOM_EMPTY_MENU,

  // Balkongen (Intermediary check + menyer)
  SCENE_BALCONY_INTERMEDIARY_1,
  SCENE_BALCONY_START_TEXT,
  SCENE_BALCONY_MENU_NONE,
  SCENE_BALCONY_MENU_NAME,
  SCENE_BALCONY_MENU_GUN,
  SCENE_BALCONY_MENU_BOTH,
  SCENE_BALCONY_GUN_TESTER,
  SCENE_BALCONY_GUN_TESTER_TWO,

  SCENE_BALCONY_DRAW_GUN_SUCCESS_TEXT,
  SCENE_BALCONY_DRAW_GUN_FAIL_TEXT,

  SCENE_BALCONY_INTERMEDIARY_2,
  SCENE_BALCONY_DIALOGUE_1_TEXT,
  SCENE_BALCONY_DIALOGUE_1_MENU_NONE,
  SCENE_BALCONY_DIALOGUE_1_MENU_EMMA,

  SCENE_BALCONY_DIALOGUE_2_TEXT,
  SCENE_BALCONY_DIALOGUE_2_MENU,

  SCENE_BALCONY_CONVINCE_SUCCESS_TEXT,
  SCENE_BALCONY_CONVINCE_FAIL_TEXT,
  SCENE_BALCONY_SACRIFICE_TEXT,

  TOTAL_SCENES
} SceneIndex;

extern const Scene story_scenes[];
#endif